version: "3"
services:
  python3:
    restart: always
    build: "./docker/"
    container_name: "apachelog_python3"
    ports:
      - "8000:8000"
    environment:
      TZ: Asia/Tokyo
    working_dir: "/root/"
    command: "tail -f /dev/null"
    volumes:
      - ./script:/root/script/
      - ./log_file:/root/log_file/
